[[getting_started]]
= Getting Started

You can generate a template skeleton based on the Meta-Template BootHub template by using the
https://boothub.org/app#/home/true/https%3A%2F%2Fgithub.com%2Fboothub-org%2Fboothub-meta-template%2Freleases%2Fdownload%2Fv{project-version}%2Fmeta-template-{project-version}.zip[BootHub GUI, role="external", window="_blank"]
or the
https://boothub.org/app#/cli[BootHub CLI, role="external", window="_blank"].

After providing the http://doc.boothub.org/releases/latest/#template-independent-data[template-independent data], you need to configure the
template-ID and provide a short description of your template:

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

Template ID [com.github.my-template]:
Short description: <span class="yellow">A BootHub template for my side projects.</span>

</pre>
</div>
<pre>

</pre>
++++

Then you need to specify whether the projects generated by your template will produce Maven-compatible artifacts:

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

Is your template intended to be used for generating projects that produce Maven-compatible artifacts? (Y/N) [Y]:

</pre>
</div>
<pre>

</pre>
++++

Usually, only projects written in a JVM language can produce Maven-compatible artifacts.
For all other project types your answer to the above question should be `N`, in which case you need to specify if the generated projects require license and versioning support:

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

Should your template require a license for the generated projects? (Y/N) [Y]:
Should your template require project versioning? (Y/N) [Y]:

</pre>
</div>
<pre>

</pre>
++++

If your projects should generate Maven-compatible artifacts, the meta-template automatically configures support for licensing and project versioning,
but you need to answer additional questions regarding the template you want to create:

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

Is your template intended to be used for generating gradle-based projects? (Y/N) [Y]:

</pre>
</div>
<pre>

</pre>
++++

If you opt for gradle-based projects, the generated template is able to create gradle build scripts customized in accordance with the answers you provide to the subsequent questions.

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

Should the gradle script of the projects generated by your template provide support for publishing artifacts to Bintray? (Y/N) [Y]:

</pre>
</div>
<pre>

</pre>
++++

If you opt for Bintray support, the gradle scripts created by your template will provide the `bintrayUpload` task, which allows you to publish artifacts to https://bintray.com/[Bintray].

Then, you need to specify the structure of the generated projects:

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

What kind of structure should have the projects generated by your template?
  1: Only single-module projects
  2: Only multi-module projects
  3: Both single-module and multi-module projects
Enter your choice:

</pre>
</div>
<pre>

</pre>
++++

The final piece of information you need to provide concerns the type of projects your template will create:

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

What type of projects should your template generate?
  1: Only applications (the generated projects will provide a main class)
  2: Only libraries (the generated projects will not provide a main class)
  3: Both applications and libraries (the generated projects may or may not provide a main class)
Enter your choice:

</pre>
</div>
<pre>

</pre>
++++
