[[introduction]]
= Introduction

TIP: Click https://boothub.org/app#/home/true/https%3A%2F%2Fgithub.com%2Fboothub-org%2Fboothub-meta-template%2Freleases%2Fdownload%2Fv{project-version}%2Fmeta-template-{project-version}.zip[here, role="external", window="_blank"] to start using the Meta-Template.

The Meta-Template BootHub template lets you create BootHub templates.

It allows you to customize the created template in accordance with the type of projects you intend to generate with it.
The project features you can opt for while configuring the created template include:

- the ability to produce Maven-compatible artifacts
- software license support
- project versioning support
- support for gradle-based projects
- support for single-module projects, multi-module projects or both
- support for libraries, applications or both
- Bintray upload support

NOTE: The source code is available on https://github.com/boothub-org/boothub-meta-template[GitHub] and is licensed under the {blob-root}/LICENSE[Apache-2.0 license].

